---
title: "SAL 605 Assignment 1"
author: "Andrew Fish"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##packages
library(tidyverse)
library(Lahman)
library(ggplot2)
library(ggthemes)
```

#1.
I will be looking at the Boston Red Sox from 2004 to 2007, specifically the batters (since using a batting stat).

```{r}
##only want batters so will take a dataframe of all non pitchers
positions <- Fielding %>%
  ##grabs all boston players from 2004 to 2007
  filter(teamID == 'BOS', yearID %in% c(2004:2007)) %>%
  select(playerID, yearID, POS)
```


```{r}
##will look at the Boston Red Sox Roster from 2004-07 when they broke the curse and won it all again 3 years later
##assuming there will be some guys around their peaks during that time
##will use Lahman to select players that played for BOS during those years
boston_rosters <- Batting %>%
  ##grabs only boston players in the years 2004 to 2007
  filter(teamID == 'BOS', yearID %in% c(2004:2007)) %>%
  ##grouping this way to help check if players had multiple boston stints in the same year (visually)
  group_by(playerID) %>% 
  inner_join(., People, by = join_by('playerID')) %>%
  inner_join(., positions, by = join_by('playerID', 'yearID')) %>%
  ##eliminating duplicates of playerID created by player being on team multiple years (career trajectory)
  slice(1) %>%
  ungroup() %>% 
  ##creates a subset removing any pitchers
  subset(., POS != 'P') %>% 
  ##will use playerID as a unique identifier
  select(playerID, nameFirst, nameLast)
```

#2.

```{r}
get_stats <- function(player.id) {
  Batting %>%
    filter(playerID == player.id) %>% 
    inner_join(., People, join_by('playerID')) %>% 
    ##since MLB has age based on June 30 need to adjust the birth year of players for simple math
    ##if born after June 30 adds a year to birthyear to account for this rule
    mutate(birthyear = case_when(birthMonth >= 7 ~ birthYear + 1,
                                 .default = birthYear),
           ##calculating age subtract current year nd birth year
           Age = yearID - birthyear,
           ##Total Bases stat will be used later just makes easier to read later formula
           TotalBases = H + 2 * X2B + 3 * X3B + 4 * HR,
           ##Runs Created it is rounded to 2 decimal places
           RunsCreated = round(((H + BB) * TotalBases) / (AB + BB), 2)) %>%
    ##only taking necessary columns Age and our stat Runs Created
    select(Age, RunsCreated)
}
```


```{r}
fit_model <- function(d) {
  fit <- lm(RunsCreated ~ I(Age - 30) + I((Age - 30) ^ 2), data = d)
  ##coefficients of the model to be used later
  b <- coef(fit)
  ##calculating max age and max runs created the x, y value of the "peak"
  max_age <- 30 - b[2] / (2 * b[3])
  max_rc <- b[1] - ((b[2] ^2) / (4 * b[3]))
  ##gives the output a list so can pull each part of the function
  list(fit = fit, max_age = max_age, max_rc = max_rc)
}
```


```{r}
##collecting all the peak information for the entire roster
##dummy vectors to be added to later
bos_peak_age <- c()
bos_peak_rc <- c()

##loop that will go through entire boston_roster playerIDs
for (i in 1:length(boston_rosters$playerID)){
  ##pulls the stats for each plater
  player_stats <- get_stats(boston_rosters$playerID[i])
  ##models the career for each player's stats giving the model, peak age, and peak rc
  player_traject <- fit_model(player_stats)
  ##adds the peak age and rc to the respective dummy vectors
  bos_peak_age <- append(bos_peak_age, player_traject$max_age)
  bos_peak_rc <- append(bos_peak_rc, player_traject$max_rc)
}
```


```{r}
##creates a new data frame with the necessary peak info for boston's roster
boston_peaks <- data.frame(
  playerID = boston_rosters$playerID,
  name = paste(boston_rosters$nameFirst, boston_rosters$nameLast, sep = ' '),
  Age = bos_peak_age,
  RunsCreated = bos_peak_rc) %>%
  ##removes any NA values for age ie no peak
    drop_na(Age)
```

```{r}
##modeling the peak data
boston_curve <- fit_model(boston_peaks)
##selecting fit
boston_model <- boston_curve %>%
  pluck('fit')
##ages from min to max of roster peaks
ages <- seq(min(boston_peaks$Age), max(boston_peaks$Age))
##creating table of ages and the max runs created
boston_avg_player <- tibble(Age = ages,
                            RunsCreated = boston_model$coefficients[1] +
                              boston_model$coefficients[2] * (Age - 30) +
                              boston_model$coefficients[3] * (Age - 30) ^2)
```

```{r}
##visualization of Trouts Career Trajectory using Runs Created
ggplot(boston_avg_player, aes(Age, RunsCreated)) +
  ##fitting line using quadratic
  geom_smooth(method = 'lm', se = FALSE, size = 1.25, color = 'midnightblue',
              formula = y ~ poly(x, 2, raw = TRUE)) +
  ##x and y intercepts for peak based on model
  geom_vline(xintercept = boston_curve$max_age, linetype = 2, color = 'darkslategray') + 
  geom_hline(yintercept = boston_curve$max_rc, linetype = 2, color = 'darkslategray') +
  ##labeling intercepts
  annotate(geom = 'text', x = c(31.25, 24.5), y = c(25, 73),
           label = c('Peak Age', 'Max'), size = 4) +
  ##chart labels
  labs(title = '2004-2007 Boston Red Sox Career Trajectory - Runs Created',
         x = 'Age',
         y = 'Runs Created',
         caption = 'Data from Lahman Database') + 
  ##centering chart title
  theme(plot.title = element_text(hjust = 0.5)) +
  ##chart theme
  theme_clean()
```


```{r}
ggsave('RedSoxRosterTrajectory.pdf')
```

