---
title: "SAL 602 Assignment 2"
author: "Andrew Fish"
date: "2024-10-28"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

##1.

```{r}
tour_data <- read_csv("C:/Users/Andrew Fish/Documents/Syracuse/SAL 602/Module 2/data/tour_data.csv")
golf_earnings <- read_csv("C:/Users/Andrew Fish/Documents/Syracuse/SAL 602/Module 2/data/golf_earnings.csv")
```

##2.

```{r}
tour_data %>% group_by(EVENT_NAME, NAME, YEAR) %>%
  filter(ROUND_NUM >= 4) %>%
  select(EVENT_NAME, YEAR, NAME, ROUND_NUM, SG_TOTAL) -> tournamentTourdata
```


##3.

```{r}
tournamentTourdata %>% group_by(NAME, YEAR) %>%
  summarize(avg_SG_Total = mean(SG_TOTAL)) -> avgSGTOT
```


##4.

```{r}
avgSGTOT %>% inner_join(golf_earnings, by = c("NAME", "YEAR")) -> earningsSGTOT
```

##5.

```{r}
earningsSGTOT %>%
  filter(YEAR == 2023) %>%
  select(NAME, EARNINGS) %>%
  arrange(desc(EARNINGS)) -> topEarnings
topEarnings %>% head(10) -> top10Earnings
```

```{r}
earningsSGTOT %>%
  filter(YEAR == 2023) %>%
  select(NAME, avg_SG_Total) %>%
  arrange(desc(avg_SG_Total)) -> topAvgSGTOT
topAvgSGTOT %>% head(10) -> top10avgSG
```

##6.

The total strokes gained doesn't directly cause more earnings. It is a factor. I believe that if we did this on a per game aspect we would have more conclusive findings. For now with total strokes gained you could have a great aspect paired with an average to ok aspect and not earn a lot of money but still have high total strokes gained.

