---
title: "SAL 602 Assignment 6"
author: "Andrew Fish"
date: "2024-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(Lahman)
library(baseballr)
library(ggrepel)
```

a.
```{r}
june2023_1 <- scrape_statcast_savant_batter_all("2023-06-01", "2023-06-07")
june2023_2 <- scrape_statcast_savant_batter_all("2023-06-08", "2023-06-14")
june2023_3 <- scrape_statcast_savant_batter_all("2023-06-15", "2023-06-21")
june2023_4 <- scrape_statcast_savant_batter_all("2023-06-22", "2023-06-28")
june2023_5 <- scrape_statcast_savant_batter_all("2023-06-29", "2023-06-30")
june2023 <- rbind(june2023_1, june2023_2, june2023_3, june2023_4, june2023_5)
```

```{r}
june2023 %>%
  filter(player_name == "Acuña Jr., Ronald") -> acunadata
```

b.
```{r}
acunadata %>%
  filter( description != "blocked_ball") -> acunadata
```

c.
```{r}
##creating the swing parameter know that won't swing on balls and called_strike
acunadata %>%
  mutate(Swing = case_when(
    type == "S" & description == "called_strike" ~ FALSE,
    type == "X" | type == "S" ~ TRUE,
    type == "B" ~ FALSE)) -> acunadata
```

```{r}
##creates the 14 zones of the strike zone
zones <- acunadata %>%
  group_by(zone) %>%
  summarize(
    N = n(),
    right_edge = min(1.5, max(plate_x)),
    left_edge = max(-1.5, min(plate_x)),
    top_edge = min(5, quantile(plate_z, 0.95, na.rm = TRUE)),
    bottom_edge = max(0, quantile(plate_z, 0.05, na.rm = TRUE)),
    swing_pct = sum(Swing == TRUE) / n(),
    plate_x = mean(plate_x),
    plate_z = mean(plate_z))
```

d.
```{r}
##creating strike zone
plate_width <- 17 + (9 / pi)
k_zone_plot <- ggplot(NULL, aes(x = plate_x, plate_z)) +
  geom_rect(xmin = -(plate_width / 2) / 12,
            xmax = (plate_width / 2) / 12,
            ymin = 1.5,
            ymax = 3.6, color = "black", alpha = 0) +
  coord_equal() +
  scale_x_continuous("Horizontal Location (ft.)",
                     limits = c(-2, 2)) +
  scale_y_continuous("Vertical Location (ft.)",
                     limits = c(0, 5))
```

```{r}
##combine the k_zone_plot and zones to make heat map
k_zone_plot %+% zones +
  geom_rect(aes(xmax = right_edge, xmin = left_edge,
                ymax = top_edge, ymin = bottom_edge,
                fill = swing_pct, alpha = swing_pct),
            color = "darkgreen") +
  geom_text_repel(size = 3, aes(label = round(swing_pct, 2),
                                color = swing_pct < 0.5)) +
  scale_fill_gradient(low = "blue", high = "red") +
  scale_color_manual(values = c("white", "black")) +
  guides(color = FALSE, alpha = FALSE) +
  ggtitle("Ronald Acuna Swing Percentage by Zone - June 2023")-> acunaplot
```

e.
```{r}
ggsave("C:/Users/Andrew Fish/Documents/Syracuse/SAL 602/Module 6/assignment6plot.pdf",
       plot = acunaplot)
```

