---
title: "SAL 602 Module 6 Lab 1"
author: "Andrew Fish"
date: "2024-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(baseballr)
library(tidyverse)
library(Lahman)
library(readr)
```

```{r}
statcastaug2019 <- read_csv("C:/Users/Andrew Fish/Documents/Syracuse/SAL 602/Module 6/statcastAugust2019.csv")
```

```{r}
##getting pitcher id for Jacob deGrom (2019 NL Cy Young)
statcastaug2019 %>%
  filter(player_name == "Jacob deGrom") -> deGromData
```

```{r}
deGromData %>%
  filter(description == "called_strike" | description == "ball") ->deGromcalled
```


```{r}
##creating strike zone
plate_width <- 17 + (9 / pi)
k_zone_plot <- ggplot(NULL, aes(x = plate_x, plate_z)) +
  geom_rect(xmin = -(plate_width / 2) / 12,
            xmax = (plate_width / 2) / 12,
            ymin = 1.5,
            ymax = 3.6, color = "cornflowerblue", alpha = 0) +
  coord_equal() +
  scale_x_continuous("Horizontal Location (ft.)",
                     limits = c(-2, 2)) +
  scale_y_continuous("Vertical Location (ft.)",
                     limits = c(0, 5))
```

```{r}
k_zone_plot %+% deGromData +
  aes(color = type, shape = pitch_name) + 
  geom_point() +
  ggtitle("Jacob deGrom Pitches August 2019") -> deGromPlot
```

```{r}
k_zone_plot %+% deGromData +
  aes(color = pitch_name) + 
  geom_point() +
  ggtitle("Jacob deGrom Called Pitches August 2019") -> deGromCalledPlot
```

```{r}
ggsave("C:/Users/Andrew Fish/Documents/Syracuse/SAL 602/Module 6/degromplot.pdf",
       plot = deGromPlot)
ggsave("C:/Users/Andrew Fish/Documents/Syracuse/SAL 602/Module 6/degromcalledplot.pdf",
       plot = deGromCalledPlot)
```

