---
title: "SAL 602 Assignment 3"
author: "Andrew Fish"
date: "2024-11-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(Lahman)
```

Reading in files from retrosheet

```{r}
fields <- read_csv("C:/Users/Andrew Fish/Documents/Syracuse/SAL 602/Module 3/fields.csv")
data2001 <- read_csv("C:/Users/Andrew Fish/Documents/Syracuse/SAL 602/Module 3/all2001.csv",
                     col_names = pull(fields, Header))
```

Getting player ids and assigning to respective players

```{r}
sosa_id <- People %>%
  filter(nameFirst == "Sammy", nameLast == "Sosa") %>%
  pull(retroID)
bonds_id <- People %>%
  filter(nameFirst == "Barry", nameLast =="Bonds") %>%
  pull(retroID)
gonz_id <- People %>%
  filter(nameGiven == "Luis Emilio") %>%
  pull(retroID)
```

Df with only Sosa, Bonds, and Gonzales

```{r}
hr_race01 <- data2001 %>%
  filter(BAT_ID %in% c(sosa_id, bonds_id, gonz_id))
```

Formating the Date as well as cumulative HR into df with Master data

```{r}
hr_race01 %>%
  mutate(Date = ymd(str_sub(GAME_ID, 4, 11))) %>%
  arrange(Date) %>%
  group_by(BAT_ID) %>%
  mutate(HR = ifelse(EVENT_CD == 23, 1, 0),
         cumHR = cumsum(HR)) %>%
  ungroup() %>%
  select(BAT_ID, Date, cumHR, HR) %>%
  inner_join(People, by = c("BAT_ID" = "retroID")) -> hr_ytd
```

Creating the plot

```{r}
ggplot(hr_ytd, aes(x = Date, y = cumHR, color = nameLast)) +
  geom_line() +
  geom_hline(yintercept = 70, color = "black", linetype = "longdash") +
  annotate("text", ymd("2001-04-15"), 73,
           label = "70", color = "black") +
  xlab("Date") +
  ylab("Homeruns") +
  ggtitle("2001 Homerun Race")
```

Saving the plot

```{r}
ggsave("C:/Users/Andrew Fish/Documents/Syracuse/SAL 602/Module 3/Assignment3graph.pdf")
```

