---
title: "SAL 621 Exam 2 Analytics Q2"
author: "Andrew Fish"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
```

```{r}
mls_data <- read_csv('data/MLS_2017-22.csv')
```

#Analytics Q2

```{r}
##adding dummy variables
mls_data %>% mutate(
  HomeWin = case_when(
    HomeScore > RoadScore ~ 1,
    .default = 0),
  RoadWin = case_when(
    RoadScore > HomeScore ~ 1,
    .default =  0),
  DrawWin = case_when(
    HomeScore == RoadScore ~ 1,
    .default = 0),
  RoadDog = case_when(
    HomeOdds < RoadOdds ~ 1,
    HomeOdds == RoadOdds ~ 0.5,
    .default =  0),
  HomeDog = case_when(
    RoadOdds < HomeOdds ~ 1,
    HomeOdds == RoadOdds ~ 0.5,
    .default =  0)) -> mls_data
```

We will use bet size of $1 so then to adjust for other bet sizes we can easily calculate

```{r}
##strategy only bet dogs
mls_data %>% filter(RoadDog == 1) -> rd_data
mls_data %>% filter(HomeDog == 1) -> hd_data
rd_data %>% 
  mutate(Returns = case_when(
    RoadWin == 1 ~ 1 * RoadOdds,
    .default = 0),
    Profits = Returns - 1) -> rd_data

hd_data %>%
  mutate(Returns = case_when(
    HomeWin == 1 ~ 1 * HomeOdds,
    .default = 0),
    Profits = Returns - 1) -> hd_data
```

```{r}
bind_rows(rd_data, hd_data) -> dogs_data
```

```{r}
##totals on returns and profits betting only underdog
sum(dogs_data$Returns)
sum(dogs_data$Profits)
##percent profit
(sum(dogs_data$Profits) / (sum(dogs_data$Returns) - sum(dogs_data$Profits))) * 100
```

```{r}
##strategy only bet fav
mls_data %>% filter(RoadDog == 0) -> rf_data
mls_data %>% filter(HomeDog == 0) -> hf_data
rf_data %>% 
  mutate(Returns = case_when(
    RoadWin == 1 ~ 1 * RoadOdds,
    .default = 0),
    Profits = Returns - 1) -> rf_data

hf_data %>%
  mutate(Returns = case_when(
    HomeWin == 1 ~ 1 * HomeOdds,
    .default = 0),
    Profits = Returns - 1) -> hf_data
```

```{r}
bind_rows(rf_data, hf_data) -> favs_data
```

```{r}
##totals on returns and profits betting only favorite
sum(favs_data$Returns)
sum(favs_data$Profits)
##percent profit
(sum(favs_data$Profits) / (sum(favs_data$Returns) - sum(favs_data$Profits))) * 100
```

```{r}
##examining dummy variable means we can see the percent they occur lots of HomeWins and Road Underdogs
summary(mls_data)
```


```{r}
##strategy only bet home
mls_data %>%
  mutate(
    Returns = case_when(
      HomeWin == 1 ~ 1 * HomeOdds,
      .default = 0),
    Profits = Returns - 1) -> home_data
```

```{r}
##calculating returns and profits
sum(home_data$Returns)
sum(home_data$Profits)
(sum(home_data$Profits) / (sum(home_data$Returns) - sum(home_data$Profits))) * 100
```

```{r}
sum(hd_data$Returns)
sum(hd_data$Profits)
(sum(hd_data$Profits) / (sum(hd_data$Returns) - sum(hd_data$Profits))) * 100
```

```{r}
##writing to csv to be used in Tableau
write_csv(favs_data, 'favs_data.csv')
write_csv(dogs_data, 'dogs_data.csv')
write_csv(home_data, 'home_data.csv')
write_csv(hd_data, 'hd_data.csv')
```